### PR TITLE
Revert to .NET Framework

### PR DESCRIPTION
**Pull request by Metadorius**
See https://github.com/CnCNet/xna-cncnet-client/pull/494 for details.

I already figured out most of the changes, what's left is technical work and evaluation.

Currently what's needed to be done here:
- [x] Finish the changing of FileStream constructors to old API
- [x] Decide if the backport of sockets handler is OK to use
- [x] Sort out the polyfills to use, see parent PR

### CODE REVIEW

**Comment by SadPencil** [comment]
~~I just realized that in order to keep the compatibility of both .NET 4.8 and .NET 7.0, it is better to switch this project to .NET Standard 2.0~~

Update: since we still need to determine whether the client is .NET 8 or 4.8, this project is retained as a .NET 4.8/8 project. Hmm, we need to merge this project into xna-cncnet-client considering the high coupling

**Comment by Metadorius** [comment]
I am not sure if the project can be compiled under .NET Standard though, I thought it's a pseudo target and a DLL/EXE can't be compiled this way?

**Comment by SadPencil** [comment]
> I am not sure if the project can be compiled under .NET Standard though, I thought it's a pseudo target and a DLL/EXE can't be compiled this way?

should be fine. `dotnet pack` command generates the package files needed by the client. After specifying this project as .NET Standard 2.0, when compiling the client in .NET 7, the related warning messages would not show again.

**Comment by SadPencil** [comment]
~~Check whether the second stage updater could run successfully as a single file exe. PR #6 brings a DLL dependency~~ (obsolete; not needed)

**Comment by SadPencil** [comment]
Now, this PR brings the support of the old `clientupdt.dat` updater as well as the new second stage updater. Both cases are tested on my machine.

**Review by Metadorius — COMMENTED** [review]
No complaints either, although not sure where did the .NET Standard as target idea go.

**Comment by SadPencil** [comment]
> not sure where did the .NET Standard as target idea go.

currently there are #if !NETFRAMEWORK to differ the client’s behavior in ClientUpdater library (e.g., whether .NET 4.8 or .NET 8.0 second-stage updater should be launched), so ClientUpdater.dll is not a .NET Standard library right now

**Pull request merged**
